server:
  port: 8093
management:
  endpoint:
    health:
      enabled: true
  server:
    port: 8099
spring:
    jpa:
        show-sql: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full